name: bera_tiles
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher:

  cupertino_icons: ^1.0.2
  audioplayers: ^0.19.0
  path_provider: ^2.0.1
  share: ^0.6.5+4
  fluttertoast: ^7.1.6
  rflutter_alert: ^1.1.0
  flutter_native_splash: ^1.2.0
  google_mobile_ads: ^0.13.1
  provider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - images/
    - decos/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: Varela
      fonts:
        - asset: fonts/Varela-Regular.ttf
    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf

flutter_native_splash:
    color: "#000000"
    image: images/splash_logo.png
    android: true
